environment: production
environmentCode:
name: ffc-pay-responses
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-responses

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-responses-config-map

containerSecret:
  name: ffc-pay-responses-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 250Mi
  limitCpu: 250m
  messageQueueHost: namespace.servicebus.windows.net
  acknowledgementTopicAddress: ffc-pay-acknowledgement
  returnTopicAddress: ffc-pay-return
  eventTopicAddress: ffc-pay-event
  eventsTopicAddress: ffc-pay-events
  paymentSubmitTopicAddress: ffc-pay-submit
  paymentSubmitSubscriptionAddress: ffc-pay-responses
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false  
  azureStorageCreateContainers: false
  storageContainer: dax
  inboundFolder: inbound
  archiveFolder: archive
  quarantineFolder: quarantine
  returnFolder: return
  useV2Events: true

postgresService:
  postgresDb: ffc_pay_responses
  postgresqlHost: ffc-pay-responses-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
